apiVersion: v1
kind: PersistentVolume
metadata:
  name: sbdemo-nfs-pv
  labels:
    role: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    # server ip must be changed
    server: {NFSIP}
    path: "/"
